### ISSUE TITLE
Image map to Amiga palette is incorrect

### ISSUE THREAD

**Issue by timfel** [Pixinn/rgb2amiga#2]
Right now this is using ImageMagick's quantization to reduce the number of colors in the image, after mapping the entire image to Amiga's 4096 color colorspace. But quantization can (and does) introduce mix colors again that are not part of the Amiga colorspace. So the resulting `CPalette` in the `CChunkImage` is actually not guaranteed to include only colors available on the Amiga. This is "sort of" fixed later when those colors again get converted in libamivideo, but it produces results that are less optimal than what ImageMagick could achieve.

IMO, the "correct" way to do this is to
* quantize the input to N colors
* get the unique colors
* create an `Magick::Image` as a colormap and fill it with the unique colors
* map the colors in that colormap to the nearest Amiga colors
* quantize the original image but this time using the `map` function with the colormap as input

Something like this (in `CChunkyImage::Init`)
```
  _imageRGB = img;
 
  // Constrain the colors to the provided Palette. We cannot only use the
  // default quantization, because that will introduce colorshifts to better
  // represent neighbouring pixel regions, it does not respect the colors
  // already in the image.
  _imageRGB.quantizeColors(nbColors);
  _imageRGB.quantizeDither(dither);
  _imageRGB.quantizeDitherMethod(Magick::FloydSteinbergDitherMethod);
  //_imageRGB.orderedDither("o3x3,2");
  _imageRGB.quantize();
  // now map the color reduced image using a map that only contains valid Amiga colors
  CPalette quantizedPalette = CPaletteFactory::GetInstance().GetUniqueColors(_imageRGB);
  Image map(Geometry(quantizedPalette.size(), 1), "white");
  MagickCore::PixelPacket* pixel = map.getPixels(0, 0, map.size().width(), map.size().height());
  for (std::size_t i = 0u; i < quantizedPalette.size(); ++i)
  {
    const auto nearestAmigaColor = paletteSpace.GetNearestColor(quantizedPalette[i]);
    pixel->red = nearestAmigaColor.r << (8 * (sizeof(pixel->red) - 1));
    pixel->green = nearestAmigaColor.g << (8 * (sizeof(pixel->green) - 1));
    pixel->blue = nearestAmigaColor.b << (8 * (sizeof(pixel->blue) - 1));
    ++pixel;
  }
  map.syncPixels();
  // map again from the original, which can potentially match slightly better
  _imageRGB = img;
  _imageRGB.map(map, dither);

  _palette = CPaletteFactory::GetInstance().GetUniqueColors(_imageRGB);
```

I can open a PR, but I have other changes in my fork now that I'll need to factor out

**Comment by Pixinn** [comment]
I think I read somewhere that quantize() only uses colors that are already present in the image, that's why I chose to match the Amiga color palette before quantization. Otherwise, a there is a (small) risk that the quantized image will sport two close close colors that will map to the same one of the Amiga Palette.
But I am not so sure now. It is easy to check if quantizeColors() introduces new colors, I will do it.

**Comment by Pixinn** [comment]
If it does, you solution is elegant.

**Comment by Pixinn** [comment]
You are right, quantize() modify the colors. I will correct the issue. Thanks for reporting.

**Comment by Pixinn** [comment]
I got the proper modification from your pull request. I close the issue.
